
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

// Clean old caches
cleanupOutdatedCaches();

// Claim clients
clientsClaim();

// Precache all assets generated by vite
precacheAndRoute(self.__WB_MANIFEST);

// Skip waiting
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Push Notification Event
self.addEventListener('push', (event) => {
  let data = { title: 'محفظتي', body: 'لديك تنبيه جديد من تطبيق محفظتي' };
  
  if (event.data) {
    try {
      data = event.data.json();
    } catch (e) {
      data = { title: 'محفظتي', body: event.data.text() };
    }
  }

  const options = {
    body: data.body,
    icon: 'https://vgosloxhrahixrduuzkt.supabase.co/storage/v1/object/public/assets/icon-192.png',
    badge: 'https://vgosloxhrahixrduuzkt.supabase.co/storage/v1/object/public/assets/icon-192.png',
    vibrate: [100, 50, 100],
    data: {
      url: data.url || '/'
    }
  };

  event.waitUntil(
    self.registration.showNotification(data.title, options)
  );
});

// Notification Click Event
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  
  event.waitUntil(
    clients.matchAll({ type: 'window' }).then((clientList) => {
      const url = event.notification.data.url;
      for (const client of clientList) {
        if (client.url === url && 'focus' in client) {
          return client.focus();
        }
      }
      if (clients.openWindow) {
        return clients.openWindow(url);
      }
    })
  );
});
